# This file was generated by GoReleaser. DO NOT EDIT.
cask "satuctl" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "08148df40354284fa0f50366d7348d709c9f94c2cf32cbe8836708fdfc774d5a"
      url "https://github.com/satuskycloud/1ctl/releases/download/v#{version}/1ctl-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "123e608979ac4fe296b5a062ae9077877040369cc0f9f84c83a8de772e26d8a9"
      url "https://github.com/satuskycloud/1ctl/releases/download/v#{version}/1ctl-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "38b9c2dbb4aa1189412aba62a9c4acf3b5bb20852f1bba41a71416d76661909a"
      url "https://github.com/satuskycloud/1ctl/releases/download/v#{version}/1ctl-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "c9dd6db790a0dafb07d1bfc28857c011dca112fc538e99b26cc394f271c9865c"
      url "https://github.com/satuskycloud/1ctl/releases/download/v#{version}/1ctl-#{version}-linux-arm64.tar.gz"
    end
  end

  name "satuctl"
  desc "CLI for SatuSky Cloud Platform"
  homepage "https://github.com/SatuSkyCloud/1ctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "1ctl"

  # No zap stanza required

end
