# This file was generated by GoReleaser. DO NOT EDIT.
cask "satuctl" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "34d1be47fe35fc77c23476c7cee512c33d1fecb7b26c4f3bb9e661c61eb1d719"
      url "https://github.com/satuskycloud/1ctl/releases/download/v#{version}/1ctl-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "f3397651626616f28a905c1f943c5ff83f3b83f88e792233c285e4fe936ffcb1"
      url "https://github.com/satuskycloud/1ctl/releases/download/v#{version}/1ctl-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd0e24fd21dc78934f2ba80d9d0fd8535f5a3c44d37e9c7ff9e2607d0bc3d752"
      url "https://github.com/satuskycloud/1ctl/releases/download/v#{version}/1ctl-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "f120d25e9e24a86705a500c51b5d2deadec7747e14f7115bd11348670e8d8c83"
      url "https://github.com/satuskycloud/1ctl/releases/download/v#{version}/1ctl-#{version}-linux-arm64.tar.gz"
    end
  end

  name "satuctl"
  desc "CLI for SatuSky Cloud Platform"
  homepage "https://github.com/SatuSkyCloud/1ctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "1ctl"

  # No zap stanza required

end
