# This file was generated by GoReleaser. DO NOT EDIT.
cask "satuctl" do
  version "0.11.1"

  on_macos do
    on_intel do
      sha256 "9d5c9777a108306e34223fda5ed1079ce9169f0c0eba67863a4e36d55c76b3ae"
      url "https://github.com/satuskycloud/1ctl/releases/download/v#{version}/1ctl-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "9d4b33ca0a9b49ffe32a91265bbd1fb1966604eecbb70b3a65cfcb9a728016ad"
      url "https://github.com/satuskycloud/1ctl/releases/download/v#{version}/1ctl-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4e1e46855dd58865cc732436a9ca9ae38555bbf87f6ce63e74127c82dea6d3b7"
      url "https://github.com/satuskycloud/1ctl/releases/download/v#{version}/1ctl-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "61f3b0af76dae4e84d178508dbac2d3fe093bad1d3f4f25c88fe28aecfff9424"
      url "https://github.com/satuskycloud/1ctl/releases/download/v#{version}/1ctl-#{version}-linux-arm64.tar.gz"
    end
  end

  name "satuctl"
  desc "CLI for SatuSky Cloud Platform"
  homepage "https://github.com/SatuSkyCloud/1ctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "1ctl"

  # No zap stanza required

end
