# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class 1ctl < Formula
  desc "CLI for SatuSky Cloud Platform"
  homepage "https://github.com/SatuSkyCloud/1ctl"
  version "0.5.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.5.11/1ctl-0.5.11-darwin-amd64.tar.gz"
      sha256 "17b45d6e3f61c96287fc5cf4883175b42c9d0e1d997dcd55c3ee17c490946a73"

      define_method(:install) do
        bin.install "1ctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.5.11/1ctl-0.5.11-darwin-arm64.tar.gz"
      sha256 "c2bcb8c9df871b6227618350f1a8952b4dc761e1d372f2de1eff0e9d0e22d4b1"

      define_method(:install) do
        bin.install "1ctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.5.11/1ctl-0.5.11-linux-amd64.tar.gz"
      sha256 "c945e5c784209527a4093e78ccd983bdb76a1a452f7a8dadb56f8ea2da0f322c"
      define_method(:install) do
        bin.install "1ctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.5.11/1ctl-0.5.11-linux-arm64.tar.gz"
      sha256 "55183eea9bb0aca60849900ad0e1d69158954cb09db85f8ef33c9ba41c535666"
      define_method(:install) do
        bin.install "1ctl"
      end
    end
  end

  test do
    assert_match "1ctl version", shell_output("#{bin}/1ctl --version")
  end
end
