# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class 1ctl < Formula
  desc "CLI for SatuSky Cloud Platform"
  homepage "https://github.com/SatuSkyCloud/1ctl"
  version "0.5.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.5.10/1ctl-0.5.10-darwin-amd64.tar.gz"
      sha256 "64e0bd77098c0da39aa21a3572a4b1b848cf6b6e86d83c1bdee25e8c913f7d9f"

      define_method(:install) do
        bin.install "1ctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.5.10/1ctl-0.5.10-darwin-arm64.tar.gz"
      sha256 "107a455c7832b4fd6b316266509fb44fe4a97bb25eb9047e4b1229bc2da5a869"

      define_method(:install) do
        bin.install "1ctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.5.10/1ctl-0.5.10-linux-amd64.tar.gz"
      sha256 "0b99d3df72ef5cac3900a10c99391902a473f142c244deb194ab5a87263923bf"
      define_method(:install) do
        bin.install "1ctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.5.10/1ctl-0.5.10-linux-arm64.tar.gz"
      sha256 "bec61a6646ba6881cdd1148c5916a3af2efc94eadda86ad1423976487d706f6e"
      define_method(:install) do
        bin.install "1ctl"
      end
    end
  end

  test do
    assert_match "1ctl version", shell_output("#{bin}/1ctl --version")
  end
end
