# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Satuctl < Formula
  desc "CLI for SatuSky Cloud Platform"
  homepage "https://github.com/SatuSkyCloud/1ctl"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.6.1/1ctl-0.6.1-darwin-amd64.tar.gz"
      sha256 "755b3984d172b19e8b69ae15806287399607a36a44362b6ff2b3ad28b78ff606"

      define_method(:install) do
        bin.install "1ctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.6.1/1ctl-0.6.1-darwin-arm64.tar.gz"
      sha256 "f8fe0f7c41212d56c06d75f7eba0e8050918ec4f41994f1f8e673391e1cc96e9"

      define_method(:install) do
        bin.install "1ctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.6.1/1ctl-0.6.1-linux-amd64.tar.gz"
      sha256 "b8a350668ae0aa96a77096eee0d91657ec56bc18e564785d4b7b6311c72785a3"
      define_method(:install) do
        bin.install "1ctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.6.1/1ctl-0.6.1-linux-arm64.tar.gz"
      sha256 "c2cbc9af16f8fffb240aeb6f20711d07addb0840261d7fe9bf879e4808cdc7ec"
      define_method(:install) do
        bin.install "1ctl"
      end
    end
  end

  test do
    assert_match "1ctl version", shell_output("#{bin}/1ctl --version")
  end
end
