# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Satuctl < Formula
  desc "CLI for SatuSky Cloud Platform"
  homepage "https://github.com/SatuSkyCloud/1ctl"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.9.1/1ctl-0.9.1-darwin-amd64.tar.gz"
      sha256 "bdc88b9820065aa2dc5314269a65807b834e81e329b18bab897fc8b954c64e14"

      define_method(:install) do
        bin.install "1ctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.9.1/1ctl-0.9.1-darwin-arm64.tar.gz"
      sha256 "fcb7ab028343fae0f35178e35f8a264473288761f80b35aec6c52dfaabe1ae83"

      define_method(:install) do
        bin.install "1ctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.9.1/1ctl-0.9.1-linux-amd64.tar.gz"
      sha256 "67c49ae1bc1e8bf54721372e9e9c7d0bea740e78fbad07b10348c3a866724a7f"
      define_method(:install) do
        bin.install "1ctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.9.1/1ctl-0.9.1-linux-arm64.tar.gz"
      sha256 "71248ebc2803f81e84342c091478a81db484b15f93815983faf2bccbb0414518"
      define_method(:install) do
        bin.install "1ctl"
      end
    end
  end

  test do
    assert_match "1ctl version", shell_output("#{bin}/1ctl --version")
  end
end
