# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Satuctl < Formula
  desc "CLI for SatuSky Cloud Platform"
  homepage "https://github.com/SatuSkyCloud/1ctl"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.6.0/1ctl-0.6.0-darwin-amd64.tar.gz"
      sha256 "815938bd78d3c9e95e8af57b98152c695e3689247d19b0be0bf6be40534aba95"

      define_method(:install) do
        bin.install "1ctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.6.0/1ctl-0.6.0-darwin-arm64.tar.gz"
      sha256 "65b028bfab47dd6c41a556796dd49fc68704e35474439775df32f2d827b5eb0d"

      define_method(:install) do
        bin.install "1ctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.6.0/1ctl-0.6.0-linux-amd64.tar.gz"
      sha256 "9705e47137b71c4e5b734dc369d3da2c4a3e2174663ed3cb255cf038a2fda2bc"
      define_method(:install) do
        bin.install "1ctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/satuskycloud/1ctl/releases/download/v0.6.0/1ctl-0.6.0-linux-arm64.tar.gz"
      sha256 "9f19dd59b91f812146760e4db65a339818219a6c1becdd3b58ccbcc6f3704fef"
      define_method(:install) do
        bin.install "1ctl"
      end
    end
  end

  test do
    assert_match "1ctl version", shell_output("#{bin}/1ctl --version")
  end
end
